<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" />
    <PackageReference Include="Npgsql" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FIAP.CloudGames.Application\FIAP.CloudGames.Application.csproj" />
    <ProjectReference Include="..\FIAP.CloudGames.Domain\FIAP.CloudGames.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\Modules\Catalog\Infrastructure\**\*.cs" Link="Catalog\%(RecursiveDir)%(Filename)%(Extension)" />
    <Compile Include="..\Modules\Acquisition\Infrastructure\**\*.cs" Link="Acquisition\%(RecursiveDir)%(Filename)%(Extension)" />
    <Compile Include="..\Modules\Logging\Infrastructure\**\*.cs" Link="Logging\%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
