// <auto-generated />
using System;
using FIAP.CloudGames.Infrastructure.Data.EF.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FIAP.CloudGames.Infrastructure.Data.EF.Migrations.Acquisition
{
    [DbContext(typeof(AcquisitionDbContext))]
    [Migration("20260825143058_AcquisitionInitial")]
    partial class AcquisitionInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("acquisition")
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FIAP.CloudGames.Domain.Entities.Aquisicao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<Guid>("JogoId")
                        .HasColumnType("uuid")
                        .HasColumnName("jogo_id");

                    b.Property<DateTimeOffset>("DataAquisicao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_aquisicao");

                    b.HasKey("Id", "UsuarioId", "JogoId")
                        .HasName("pk_aquisicoes");

                    b.ToTable("aquisicoes", "acquisition");
                });
#pragma warning restore 612, 618
        }
    }
}
