// <auto-generated />
using System;
using FIAP.CloudGames.Infrastructure.Data.EF.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FIAP.CloudGames.Infrastructure.Data.EF.Migrations
{
    [DbContext(typeof(PostgresqlDbContext))]
    partial class PostgresqlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FIAP.CloudGames.Domain.Entities.Aquisicao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<Guid>("JogoId")
                        .HasColumnType("uuid")
                        .HasColumnName("jogo_id");

                    b.Property<DateTimeOffset>("DataAquisicao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_aquisicao");

                    b.HasKey("Id", "UsuarioId", "JogoId")
                        .HasName("pk_aquisicoes");

                    b.HasIndex("JogoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("aquisicoes", (string)null);
                });

            modelBuilder.Entity("FIAP.CloudGames.Domain.AccessControl.Entities.Autorizacao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("JogoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("JogoId");

                    b.HasIndex("UsuarioId", "JogoId")
                        .IsUnique();

                    b.ToTable("tb_Autorizacao", (string)null);
                });

            modelBuilder.Entity("FIAP.CloudGames.Domain.Catalog.Entities.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("tb_Categorias", (string)null);
                });

            modelBuilder.Entity("FIAP.CloudGames.Domain.Catalog.Entities.CategoriaJogo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("JogoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("JogoId", "CategoriaId")
                        .IsUnique();

                    b.ToTable("rel_CategoriaJogo", (string)null);
                });

            modelBuilder.Entity("FIAP.CloudGames.Domain.Catalog.Entities.Jogo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset>("DataCadastro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<string>("FaixaEtaria")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("faixa_etaria");

                    b.Property<decimal>("Preco")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("preco");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("titulo");

                    b.HasKey("Id")
                        .HasName("pk_jogos");

                    b.ToTable("jogos", (string)null);
                });

            modelBuilder.Entity("FIAP.CloudGames.Domain.Entities.LogJogo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataCriacao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Descricao");

                    b.Property<Guid>("JogoId")
                        .HasColumnType("uuid")
                        .HasColumnName("JogoId");

                    b.HasKey("Id");

                    b.HasIndex("JogoId");

                    b.ToTable("tb_LogJogos", (string)null);
                });

            modelBuilder.Entity("FIAP.CloudGames.Domain.Entities.LogUsuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataCriacao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Descricao");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("UsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("tb_LogUsuarios", (string)null);
                });

            modelBuilder.Entity("FIAP.CloudGames.Domain.Identity.Entities.Perfil", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Nome");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("tb_Perfil", (string)null);
                });

            modelBuilder.Entity("FIAP.CloudGames.Domain.AccessControl.Entities.Permissao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("PerfilId")
                        .HasColumnType("uuid")
                        .HasColumnName("perfil_id");

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.HasKey("Id", "PerfilId")
                        .HasName("pk_permissoes");

                    b.HasIndex("PerfilId");

                    b.ToTable("permissoes", (string)null);
                });

            modelBuilder.Entity("FIAP.CloudGames.Domain.Entities.Token", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataExpiracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataRevogacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenValue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Token");

                    b.HasKey("Id");

                    b.ToTable("tb_Tokens", (string)null);
                });

            modelBuilder.Entity("FIAP.CloudGames.Domain.Identity.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cpf");

                    b.Property<DateTimeOffset>("CriadoEmUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em_utc");

                    b.Property<DateTimeOffset?>("DataInativacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_inativacao");

                    b.Property<DateTimeOffset>("DataNascimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_nascimento");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("PerfilId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("perfil_id");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("senha_hash");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_usuarios_email");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("FIAP.CloudGames.Domain.Entities.Aquisicao", b =>
                {
                    b.HasOne("FIAP.CloudGames.Domain.Catalog.Entities.Jogo", null)
                        .WithMany()
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_aquisicoes_jogos");

                    b.HasOne("FIAP.CloudGames.Domain.Identity.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_aquisicoes_usuarios");
                });

            modelBuilder.Entity("FIAP.CloudGames.Domain.AccessControl.Entities.Autorizacao", b =>
                {
                    b.HasOne("FIAP.CloudGames.Domain.Catalog.Entities.Jogo", null)
                        .WithMany()
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FIAP.CloudGames.Domain.Identity.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FIAP.CloudGames.Domain.Catalog.Entities.CategoriaJogo", b =>
                {
                    b.HasOne("FIAP.CloudGames.Domain.Catalog.Entities.Categoria", null)
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FIAP.CloudGames.Domain.Catalog.Entities.Jogo", null)
                        .WithMany()
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FIAP.CloudGames.Domain.Entities.LogJogo", b =>
                {
                    b.HasOne("FIAP.CloudGames.Domain.Catalog.Entities.Jogo", null)
                        .WithMany()
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FIAP.CloudGames.Domain.Entities.LogUsuario", b =>
                {
                    b.HasOne("FIAP.CloudGames.Domain.Identity.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FIAP.CloudGames.Domain.AccessControl.Entities.Permissao", b =>
                {
                    b.HasOne("FIAP.CloudGames.Domain.Identity.Entities.Perfil", null)
                        .WithMany()
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
