<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FIAP.CloudGames.Domain\FIAP.CloudGames.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\Modules\Identity\Application\**\*.cs" Link="Identity\%(RecursiveDir)%(Filename)%(Extension)" />
    <Compile Include="..\Modules\Catalog\Application\**\*.cs" Link="Catalog\%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
