<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <Compile Include="..\Modules\Catalog\Domain\**\*.cs" Link="Catalog\%(RecursiveDir)%(Filename)%(Extension)" />
    <Compile Include="..\Modules\Acquisition\Domain\**\*.cs" Link="Acquisition\%(RecursiveDir)%(Filename)%(Extension)" />
    <Compile Include="..\Modules\Logging\Domain\**\*.cs" Link="Logging\%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
