<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <Compile Include="..\Modules\Identity\Domain\**\*.cs" Link="Identity\%(RecursiveDir)%(Filename)%(Extension)" />
    <Compile Include="..\Modules\Catalog\Domain\**\*.cs" Link="Catalog\%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
